/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author alber
 */
public class menuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnactualizarAct = new javax.swing.JButton();
        btnagregarAct = new javax.swing.JButton();
        btneliminarAct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnactualizarCua = new javax.swing.JButton();
        btnagregarCua = new javax.swing.JButton();
        btneliminarCua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnactualizarEmp = new javax.swing.JButton();
        btnagregarEmp = new javax.swing.JButton();
        btneliminarEmp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnactualizarLug = new javax.swing.JButton();
        btnagregarLug = new javax.swing.JButton();
        btneliminarLug = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblAdmin.setText("Administrador ");

        jLabel1.setText("Actividad:");

        btnactualizarAct.setText("Actualizar");
        btnactualizarAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActActionPerformed(evt);
            }
        });

        btnagregarAct.setText("Agregar");
        btnagregarAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActActionPerformed(evt);
            }
        });

        btneliminarAct.setText("Eliminar");
        btneliminarAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActActionPerformed(evt);
            }
        });

        jLabel2.setText("Cuadrilla:");

        btnactualizarCua.setText("Actualizar");
        btnactualizarCua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarCuaActionPerformed(evt);
            }
        });

        btnagregarCua.setText("Agregar");
        btnagregarCua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarCuaActionPerformed(evt);
            }
        });

        btneliminarCua.setText("Eliminar");
        btneliminarCua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarCuaActionPerformed(evt);
            }
        });

        jLabel3.setText("Empleado:");

        btnactualizarEmp.setText("Actualizar");
        btnactualizarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarEmpActionPerformed(evt);
            }
        });

        btnagregarEmp.setText("Agregar");
        btnagregarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarEmpActionPerformed(evt);
            }
        });

        btneliminarEmp.setText("Elimnar");
        btneliminarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarEmpActionPerformed(evt);
            }
        });

        jLabel4.setText("Lugar:");

        btnactualizarLug.setText("Actualizar");
        btnactualizarLug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarLugActionPerformed(evt);
            }
        });

        btnagregarLug.setText("Agregar");
        btnagregarLug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarLugActionPerformed(evt);
            }
        });

        btneliminarLug.setText("Eliminar");
        btneliminarLug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarLugActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnactualizarAct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnagregarAct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneliminarAct))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnactualizarLug)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnagregarLug)
                                .addGap(12, 12, 12)
                                .addComponent(btneliminarLug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnactualizarEmp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnagregarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneliminarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnactualizarCua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnagregarCua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneliminarCua)))
                        .addGap(0, 187, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAdmin)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizarAct)
                    .addComponent(btnagregarAct)
                    .addComponent(btneliminarAct))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizarCua)
                    .addComponent(btnagregarCua)
                    .addComponent(btneliminarCua))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagregarEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnactualizarEmp)
                        .addComponent(btneliminarEmp)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizarLug)
                    .addComponent(btnagregarLug)
                    .addComponent(btneliminarLug))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       this.dispose();
       new Principal().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnactualizarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActActionPerformed
       this.dispose();
       new ActualizarActividad().setVisible(true);
    }//GEN-LAST:event_btnactualizarActActionPerformed

    private void btnagregarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActActionPerformed
       this.dispose();
       new AgregarActividad().setVisible(true);
    }//GEN-LAST:event_btnagregarActActionPerformed

    private void btneliminarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActActionPerformed
       this.dispose();
       new EliminarActividad1().setVisible(true);
    }//GEN-LAST:event_btneliminarActActionPerformed

    private void btnactualizarCuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarCuaActionPerformed
       this.dispose();
       new ActualizarCuadrilla().setVisible(true);
    }//GEN-LAST:event_btnactualizarCuaActionPerformed

    private void btnagregarCuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarCuaActionPerformed
       this.dispose();
       new AgregarCuadrilla().setVisible(true);
    }//GEN-LAST:event_btnagregarCuaActionPerformed

    private void btneliminarCuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarCuaActionPerformed
       this.dispose();
       new EliminarCuadrilla().setVisible(true);
    }//GEN-LAST:event_btneliminarCuaActionPerformed

    private void btnactualizarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarEmpActionPerformed
       this.dispose();
       new ActualizarEmpleado().setVisible(true);
    }//GEN-LAST:event_btnactualizarEmpActionPerformed

    private void btnagregarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarEmpActionPerformed
       this.dispose();
       new AgregarEmpleado().setVisible(true);
    }//GEN-LAST:event_btnagregarEmpActionPerformed

    private void btneliminarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarEmpActionPerformed
       this.dispose();
       new EliminarEmpleado().setVisible(true);
    }//GEN-LAST:event_btneliminarEmpActionPerformed

    private void btnactualizarLugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarLugActionPerformed
       this.dispose();
       new ActualizarLugar().setVisible(true);
    }//GEN-LAST:event_btnactualizarLugActionPerformed

    private void btnagregarLugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarLugActionPerformed
       this.dispose();
       new AgregarLugar().setVisible(true);
    }//GEN-LAST:event_btnagregarLugActionPerformed

    private void btneliminarLugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarLugActionPerformed
       this.dispose();
       new EliminarLugar().setVisible(true);
    }//GEN-LAST:event_btneliminarLugActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnactualizarAct;
    private javax.swing.JButton btnactualizarCua;
    private javax.swing.JButton btnactualizarEmp;
    private javax.swing.JButton btnactualizarLug;
    private javax.swing.JButton btnagregarAct;
    private javax.swing.JButton btnagregarCua;
    private javax.swing.JButton btnagregarEmp;
    private javax.swing.JButton btnagregarLug;
    private javax.swing.JButton btneliminarAct;
    private javax.swing.JButton btneliminarCua;
    private javax.swing.JButton btneliminarEmp;
    private javax.swing.JButton btneliminarLug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmin;
    // End of variables declaration//GEN-END:variables
}
